### ISSUE TITLE
Full Implementation Pull Request

### ISSUE THREAD

**Issue by averydl** [arielmukadi/Adapter#1]
You need to submit a pull request w/ full implementation in a new repository so that I can do your code review

**Comment by arielmukadi** [comment]
I did it very sorry for the delay

**Comment by arielmukadi** [comment]
tell me if you find anything wrong that you will like me to fix I am just getting my way around github

**Comment by CptnYankee** [comment]
Oh, you need to make a new branch, call it code review or something. Then upload all the files to that branch from your computer. Then make a pull request. It will show up and people can comment on it.

**Comment by averydl** [comment]
No worries; I see the new repository, but there are a few things you'll need to do before I can review your code. In the new repo, you need to: 

1 - Create a new branch
2 - Add all of your source code
3 - Push the branch to github
4 - Open a pull request for the new branch with all of your code

After you do this i can review/comment on your code

**Comment by arielmukadi** [comment]
how about now

**Comment by averydl** [comment]
Just do step 4 from above; open the 'branches' tab, click on the new 'code-review' branch you made, and then click 'new pull request'.

**Comment by arielmukadi** [comment]
I did it can you check please

**Comment by arielmukadi** [comment]
did everything okay

**Comment by averydl** [comment]
It looks like you might have just merged your branch. I ended up reviewing another repo, so no worries. You might want to email Sara to confirm.

**Comment by arielmukadi** [comment]
what do you mean?
yes I did it because it aske me to do so did you see my files

**Comment by averydl** [comment]
I see your code, but the issue is that without an open pull request I can't add in-line comments to your code.

**Comment by arielmukadi** [comment]
I sent you a new one check you will see

**Comment by arielmukadi** [comment]
i meant I sent you a new invite
